import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Layout from '../components/Layout';
import Gallery from '../components/Gallery';
import { fetchDataKeyword } from '../lib/keyword';


export async function getServerSideProps() {
  const allWorksData = await fetchDataKeyword();
  return {
    props: {
      objects: allWorksData
    }
  }
}

export default function Home(props) {
  let objects = props.objects.objectIDs.splice(0,20)
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Gallery App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Gallery objects={objects}/>
        </main>

        <footer className={styles.footer}>
          Gallery | Copyright 2021
        </footer>
      </div>
    </Layout>
  )
}
